version: "3.9"
volumes:
  data:
services:
  app:
    ports:
      - "3000:3000"
    build:
      dockerfile: dev.Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
    links:
      - db
    environment:
      DATABASE_URL: postgres://local-dev@db/api?sslmode=disable
  db:
    ports:
      - "5432:5432"
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: local-dev
      POSTGRES_HOST_AUTH_METHOD: trust

  migrate: &basemigrate
    profiles: [ "tools" ]
    image: migrate/migrate
    entrypoint: "migrate -database postgresql://local-dev@db/api?sslmode=disable -path /tmp/migrations"
    command: up
    links:
      - db
    volumes:
      - ./migrations:/tmp/migrations

  create-migration:
    <<: *basemigrate
    entrypoint: migrate create -dir /tmp/migrations -ext sql
    command: ""