GET {{protocol}}{{host}}:{{port}}/api/v1/leagues

###

PUT {{protocol}}{{host}}:{{port}}/api/v1/league
Content-Type: application/json

{
  "name": "Creepcamp League",
  "startDate": "2023-07-17T07:45:42.914Z",
  "endDate": "2023-07-25T07:45:42.914Z",
  "type": "League",
  "website": "https://creepcamp.de/"
}

### Get a single League from the database

GET {{protocol}}{{host}}:{{port}}/api/v1/leagues/{{leagueId}}
