---
title: Warcraft III Game Tracker
---
erDiagram
    TOURNAMENT {
        id UUID
        name string
        type string
        start_date Date
        end_date Date
        max_participants int
    }
    PARTICIPANT {
        id UUID
        name string
        contact_info string
        wins int
        losses int
        rank int
    }
    TEAM {
        id UUID
        name string
        member_ids List
    }
    MATCH {
        id UUID
        participant1_id UUID
        participant2_id UUID
        match_date Date
        outcome UUID
    }
    ROUND {
        round_id UUID
        match_ids List
        round_number string
    }
    BRACKET {
        id UUID
        round_ids List
    }
    GAME_MAP {
        id UUID
        name string
    }
    HERO_UNIT {
        id UUID
        name String
    }
    PARTICIPANT ||--|{ TEAM : "is part of"
    PARTICIPANT }|--|{ MATCH : "competes in"
    TEAM }|--|{ MATCH : "competes in"
    MATCH ||--|| ROUND : "is part of"
    ROUND ||--|| BRACKET : "is part of"
    BRACKET ||--|| TOURNAMENT : "is part of"
    MATCH ||--|| GAME_MAP : "played on"
    MATCH ||--|{ HERO_UNIT : "used in"
    TOURNAMENT ||--|{ PARTICIPANT : "has"
